### ISSUE TITLE
Version should be 0.40

### ISSUE THREAD

**Issue by yomybaby** [benbahrenburg/benCoding.Android.Tools#18]
previous version is 0.34.
current version is 0.4.

34 bigger then 4. 

:)

https://github.com/benbahrenburg/benCoding.Android.Tools/commit/3490d31b83659070e334a0ea3d663da716a7dee7#diff-7f5cb74af5d7f4b82200738fdbdc5a45L5

**Comment by benbahrenburg** [comment]
Thanks, updated.
